  {
    "application": "{{ var "application" }}",
    "keepWaitingPipelines": false,
    "name": "{{var "application" }}",
    "limitConcurrent": true,

    "stages": [

      {{ module "stage.bakeManifest.module" 
          "name" "{{ var "application" }}"
          "refId" 1	
          "requisiteStageRefIds" []

          "templateRenderer" "HELM2"
          "outputName" "bake-artifact-output"
          "namespace" "karlo"
          
      }},
      {{ module "stage.deployManifest.module" 
        "name" "deploy manifest"
        "refId" 2
        "requisiteStageRefIds" ["1"] 

        "account" "kubernetes"
        "cloudProvider" "kubernetes"
        "applicationName" "training"
        "namespaceOverride" "karlo"
        "source" "artifact"
        "manifestArtifactId" "helmBakedNginxId"
        "manifestArtifactAccount" "embedded-artifact"
        
        "requiredArtifacts" []
        "skipExpressionEvaluation" false
        "requiredArtifactIds" []
        "expectedArtifacts" []

      }}
    ],
    "triggers": [],
    "updateTs": "1567185128000"
  }