  {
    "application": "{{ var "application" }}",
    "keepWaitingPipelines": false,
    "name": "{{var "application" }}",
    "limitConcurrent": true,

    "stages": [

      {{ module "stage.bakeManifest.module" 
          "name" {{var application }}
          "refId" 1	
          "requisiteStageRefIds" []

          "templateRenderer" "HELM2"
          "outputName" "bake-artifact-output"
          "namespace" "karlo"
          
      }}
    ],
    "triggers": [],
    "updateTs": "1567185128000"
  }