{
  "name": "{{ var "name" ?: "Enable (Manifest)" }}",
  "type": "enableManifest",
  "refId": "{{ var "refId" }}",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},

  "app": "{{ var "app" }}",
  "account": "{{ var "account" }}",
  "cloudProvider": "{{ var "cloudProvider" }}",
  "location": "{{ var "location" ?: "default" }}",

  "mode": "{{ var "mode" ?: "static" }}",

  {{if eq "static" (var "mode") }}
    "manifestName": "{{ var "manifestType" }} {{ var "manifestName" }}",
  {{ end }}
  
  {{if eq "dynamic" (var "mode") }}
    "cluster": "{{ var "cluster" }}",
    "criteria": "{{ var "criteria" ?: "smallest" }}",
    "kind": "{{ var "kind" }}",
  {{ end }}

  {{ module "section.notifications.module" }}
  {{ module "section.executionOptions.module" }}
}