{
  "name": "{{ var "name" ?: "Manual Judgment" }}",
  "type": "manualJudgment",
  "refId": "{{ var "refId" }}",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},


  "instructions": "{{ var "instructions" ?: "Please Verify"}}",
  "judgmentInputs": {{ var "judgmentInputs" ?: [] }},
  
  {{ module "section.notifications.module" }}
  {{ module "section.executionOptions.module" }},

  "comments": "{{ var "comments"}}"
}