- clusters:
    - account: aws
      application: patreonpy
      associatePublicIpAddress: false
      availabilityZones:
        us-west-1:
        - us-west-1b
        - us-west-1c
      base64UserData: base64UserData
      capacity:
        desired: 1
        max: 1
        min: 1
      cloudProvider: aws
      cooldown: 10
      copySourceCustomBlockDeviceMappings: false
      delayBeforeDisableSec: 0
      delayBeforeScaleDownSec: 0
      dirty: {}
      ebsOptimized: true
      enabledMetrics: []
      freeFormDetails: api
      healthCheckGracePeriod: 600
      healthCheckType: ELB
      iamRole: iamRole
      instanceMonitoring: false
      instanceType: m5.2xlarge
      keyPair: launch_root
      loadBalancers: []
      moniker:
        app: patreonpy
        detail: api
        stack: production
      preferSourceCapacity: true
      provider: aws
      rollback:
        onFailure: false
      scaleDown: false
      securityGroups:
      - sg-01c843adf86a2caf7
      - sg-065bd460
      - sg-4e050428
      spelLoadBalancers: []
      spelTargetGroups: []
      spotPrice: ''
      stack: production
      strategy: redblack
      subnetType: ec2-private-subnets
      suspendedProcesses: []
      tags:
        environment: production
        provision_branch: master
        provisioner: spinnaker
        python_sha: ${parameters["python_sha"]}
        role: webapi-spinnaker
      targetGroups:
      - patreonpy-production-api
      targetHealthyDeployPercentage: 100
      terminationPolicies:
      - Default
      useAmiBlockDeviceMappings: false
      useSourceCapacity: true
    name: Deploy API
    overrideTimeout: true
    refId: '3'
    requisiteStageRefIds:
    - '1'
    stageTimeoutMs: 2400000
    type: deploy