- baseAmi: replace
    baseLabel: release
    baseOs: ubuntu
    cloudProviderType: aws
    extendedAttributes:
      python_sha: ${parameters["python_sha"]}
      venv_sha: ${parameters["venv_sha"]}
    name: Bake AMI
    package: none_${parameters["python_sha"]}
    refId: '1'
    region: us-west-1
    regions:
    - us-west-1
    requisiteStageRefIds:
    - '9'
    storeType: ebs
    templateFileName: tarball-shiv-install.json
    type: bake
    user: ivan.hernandez@armory.io
    vmType: hvm