- clusters:
    - account: aws
      application: patreonpy
      associatePublicIpAddress: false
      availabilityZones:
        us-west-1:
        - us-west-1b
        - us-west-1c
      base64UserData: base64UserData
      capacity:
        desired: 1
        max: 10
        min: 1
      cloudProvider: aws
      cooldown: 10
      copySourceCustomBlockDeviceMappings: false
      delayBeforeDisableSec: 0
      delayBeforeScaleDownSec: 0
      dirty: {}
      ebsOptimized: true
      enabledMetrics: []
      freeFormDetails: web
      healthCheckGracePeriod: '120'
      healthCheckType: ELB
      iamRole: tf_webpython_production
      instanceMonitoring: false
      instanceType: m5.2xlarge
      keyPair: launch_root
      loadBalancers: []
      maxRemainingAsgs: 2
      moniker:
        app: patreonpy
        detail: web
        stack: production
      preferSourceCapacity: true
      provider: aws
      rollback:
        onFailure: false
      scaleDown: false
      securityGroups:
      - sg-71070617
      - sg-065bd460
      - sg-01c843adf86a2caf7
      spelLoadBalancers: []
      spelTargetGroups: []
      spotPrice: ''
      stack: production
      strategy: redblack
      subnetType: ec2-private-subnets
      suspendedProcesses: []
      tags:
        environment: production
        provision_branch: ${parameters["provision_branch"]}
        provisioner: spinnaker
        python_sha: "${ trigger['parentExecution']['stages'][0]['context'][extendedAttributes][python_sha]}"
        role: webpython-spinnaker
      targetGroups:
      - patreonpy-production-web
      targetHealthyDeployPercentage: 100
      terminationPolicies:
      - Default
      useAmiBlockDeviceMappings: false
      useSourceCapacity: true
    name: Deploy Web
    overrideTimeout: true
    refId: '2'
    requisiteStageRefIds:
    - '1'
    stageTimeoutMs: 2400000
    type: deploy