{
  "application": "training",

  "pipelines": [
      {
        "application": "training",
        "keepWaitingPipelines": false,
        "name": "bakeAndDeploy",
        "limitConcurrent": true,

        "expectedArtifacts": [
  	       {{ module "section.artifact.module"
              "artifactId" {{var helmId}}
              "displayName" {{var helmDisplayName}}
              "artifactName" {{var helmId}}
              "artifactReference" {{var helmReference}}
              "type" "s3/object"
            }},
            
            {{ module "section.artifact.module"
              "artifactId" {{var valuesId}}
              "displayName" {{var valuesDisplayName}}
              "artifactName" {{var valuesId}}
              "artifactReference" {{var valuesReference}}
              "type" "s3/object"
            }}
				],

        "stages": [

          {{ module "stage.bakeManifest.module" 
              "name" "bake manifest"
              "refId" 1	
              "requisiteStageRefIds" []

              "templateRenderer" "HELM2"
              "outputName" "bake-artifact-output"
              "namespace" "karlo"

              "inputArtifacts" [
                {{ module "section.inputArtifact.module"
                  "account" "s3artifact"
                  "artifact" null
                  "id" {{var helmId}}
                }},
                {{ module "section.inputArtifact.module"
                  "account" "s3artifact"
                  "artifact" null
                  "id" {{var valuesId}}
                }},
              ]

              "evaluateOverrideExpressions" false

              "expectedArtifacts" [
                                    {{ module "section.artifact.module"
                                      "artifactId" {{var bakedArtifactId}}
                                      "displayName" {{var bakedArtifact}}
                                      "artifactName" {{var bakedArtifactId}}
                                      "type" "embedded/base64"
                                    }}
                                  ]
              

          }},
          {{ module "stage.deployManifest.module" 
            "name" "deploy manifest"
            "refId" 2
            "requisiteStageRefIds" ["1"] 

            "account" "kubernetes"
            "cloudProvider" "kubernetes"
            "applicationName" "training"
            "namespaceOverride" "karlo"
            "source" "artifact"
            "manifestArtifactId" "helmBakedNginxId"
            "manifestArtifactAccount" "embedded-artifact"
            

            "requiredArtifacts" []
            "skipExpressionEvaluation" false
            "requiredArtifactIds" []
            "expectedArtifacts" []

          }}

        ],
        "triggers": [],
        "updateTs": "1567185128000"
      }
   ]
}

